# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdefaults < Formula
  desc "mdefaults is a tool to manage default values of macOS."
  homepage "https://github.com/fumiya-kume/mdefaults"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.1.0/mdefaults_1.1.0_darwin_amd64.tar.gz"
      sha256 "bfdf1858c01334704134fe41a87c7811c7c35f265fb221325f9710d092e82b93"

      def install
        bin.install "mdefaults"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.1.0/mdefaults_1.1.0_darwin_arm64.tar.gz"
      sha256 "8a205cb2d436901248e530446d6d729c6f10d5fc14cbc4a84834de9ae083cc13"

      def install
        bin.install "mdefaults"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.1.0/mdefaults_1.1.0_linux_amd64.tar.gz"
        sha256 "4949032c381cbb4b97f636627c7a948299fd262f6afb59465df31af132a8cac6"

        def install
          bin.install "mdefaults"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.1.0/mdefaults_1.1.0_linux_arm64.tar.gz"
        sha256 "c700a108f7884639b1e0e77d51abe6134ca9043778f1bac13e08d3ebb9063a43"

        def install
          bin.install "mdefaults"
        end
      end
    end
  end
end
