# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdefaults < Formula
  desc "mdefaults is a tool to manage default values of macOS."
  homepage "https://github.com/fumiya-kume/mdefaults"
  version "1.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.0.18/mdefaults_1.0.18_darwin_amd64.tar.gz"
      sha256 "c2fbfe17437711f4d25b01c5f1c202c211870c18e57f297198d2865375d33987"

      def install
        bin.install "mdefaults"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.0.18/mdefaults_1.0.18_darwin_arm64.tar.gz"
      sha256 "ec7ad96cd1fbee34835b870c785711d12f3806be1385acf35c41a55f781b73a2"

      def install
        bin.install "mdefaults"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.0.18/mdefaults_1.0.18_linux_amd64.tar.gz"
        sha256 "bb1e604d7affde6393928b8e67f76dc8f3011a6675dea7a5d79b3afdbaa5e843"

        def install
          bin.install "mdefaults"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fumiya-kume/mdefaults/releases/download/v1.0.18/mdefaults_1.0.18_linux_arm64.tar.gz"
        sha256 "e167045a6fc3bf51cc90e863fef8e268c973be86dd3eacc995d42bc3106389cf"

        def install
          bin.install "mdefaults"
        end
      end
    end
  end
end
